### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by seanbudd** [yplassiard/nvda-translate#17]
The following error is occurring on the translation server, preventing translations from happening

```
svn status
mn/add-ons/instantTranslate/nvda.po:207: duplicate message definition...
mn/add-ons/instantTranslate/nvda.po:205: ...this is the location of the first definition
msgmerge: found 1 fatal error
mr addon2svn: command failed
```

**Comment by nidza07** [comment]
Hello,
unless I am mistaken, this issue should go to https://github.com/beqabeqa473/instantTranslate instead. Instant translate is a different addon, and this addon, called "Translate" isn't in the SVN system.

**Comment by seanbudd** [comment]
Apologies
