### ISSUE TITLE
{BUG} site domains stripped out of translated text

### ISSUE THREAD

**Issue by chojiro** [yplassiard/nvda-translate#2]
I noticed this when I was translating Danish text to English, and I'm not sure if it's something going on with the add-on itself since Google Translate seems to do it just fine when using the service separately from the NVDA add-on

For instance, if you have a link on the same line which contains a domain, like nvaccess.org, nvda.dk, etc, NVDA simply says link and nothing else. If you also enter it as simple text and read it using the down arrow and it is by itself on  a line, NVDA remains silent.

This is using NVDA Version: alpha-16885,2ed7dbae mind you (also attempted with NVDA 2018.4.1) and add-on release 2019.03.

**Comment by yplassiard** [comment]
Hi, this is actually an issue (bug) and I'll try to make a fix asap.
Thanks

**Comment by yplassiard** [comment]
Fixed in 2019.03.3
