### ISSUE TITLE
bug: 2019 add on is not compatible

### ISSUE THREAD

**Issue by marrie** [yplassiard/nvda-translate#5]
I went to go download the 2019 version of this add on and it is not compatible. The 2020 link actually gives a 404. Can this please be looked into? I actually miss using this add on as it enabled me to talk to someone  from china, and translate other stuff on the fly.

Thanks.

**Comment by yplassiard** [comment]
Hi, you can download the latest add-on version from:
http://www.mtyp.fr/nvda/translate/translate-2021.01.1.nvda-addon
